export const CHANGE_DEVICE = "CHANGE_DEVICE";
export const CHANGE_DEVICE_POSITION = "CHANGE_DEVICE_POSITION";
export const CHANGE_SUMMARY_DATA = "CHANGE_SUMMARY_DATE";
export const CHANGE_STARTING_DATE = "CHANGE_STARTING_DATE";
export const CHANGE_ENDING_DATE = "CHANGE_ENDING_DATE";
export const CHANGE_PLOT_TYPE = "CHANGE_PLOT_TYPE";